version: "3.9"

services:
  db:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: pelprousr
      POSTGRES_DB: pelpro
      POSTGRES_PASSWORD: pelpropass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgres/data/

  flask:
    container_name: flask
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/code
    stdin_open: true
    tty: true
    restart: always
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_RUN_HOST=0.0.0.0
    depends_on:
      - db


volumes:
  postgres_data:
