"""empty message

Revision ID: 50163df575b9
Revises: fa0dca8199d0
Create Date: 2021-02-12 08:48:34.776702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50163df575b9'
down_revision = 'fa0dca8199d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_measurement_uc', 'measurement', ['measurement_date', 'city_id', 'plant_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_measurement_uc', 'measurement', type_='unique')
    # ### end Alembic commands ###
